import { FormEvent, useEffect, useMemo, useState } from 'react'
import { supabase } from './supabase'
import biographLogoSheet from '../assets/logo-options/biograph-logo-refinements.png'

type Metric = { metric_key:string; value_numeric:number; unit:string|null; is_derived:boolean; source_timestamp:string; local_date:string; source:string }
type Note = { id:string; local_date:string; note:string }
type View = 'dashboard'|'trends'|'daily'|'records'|'sources'
type Theme = 'light'|'dark'|'permit'|'aurora'
const TZ='UTC'
const meta:Record<string,{label:string;group:string;color:string;unit?:string}>={
 weight:{label:'Weight',group:'Body',color:'#6659d8',unit:'kg'},waist:{label:'Abdominal perimeter',group:'Body',color:'#0a9488',unit:'cm'},body_fat:{label:'Body fat',group:'Composition',color:'#c34679',unit:'%'},muscle:{label:'Skeletal muscle',group:'Composition',color:'#4b70dd',unit:'%'},visceral_fat:{label:'Visceral fat',group:'Composition',color:'#df861c'},bmi:{label:'BMI',group:'Composition',color:'#8b5cce'},fat_mass:{label:'Fat mass',group:'Composition',color:'#bd4d70',unit:'kg'},fat_free_mass:{label:'Fat-free mass',group:'Composition',color:'#3c83b8',unit:'kg'},body_age:{label:'Body age',group:'Composition',color:'#a660a9',unit:'years'},bmr:{label:'Resting metabolism',group:'Energy',color:'#bd6916',unit:'kcal'},tdee:{label:'TDEE',group:'Energy',color:'#8a6d18',unit:'kcal'},steps:{label:'Steps',group:'Activity',color:'#4f870d'},calories:{label:'Calories',group:'Energy',color:'#df861c',unit:'kcal'},heart_rate:{label:'Heart rate',group:'Heart',color:'#d14c72',unit:'bpm'},systolic_bp:{label:'Systolic BP',group:'Heart',color:'#c73e55',unit:'mmHg'},diastolic_bp:{label:'Diastolic BP',group:'Heart',color:'#d66b40',unit:'mmHg'},sleep_duration:{label:'Sleep duration',group:'Sleep',color:'#5e70d5',unit:'h'},workout_duration:{label:'Workout duration',group:'Activity',color:'#129b84',unit:'min'},distance:{label:'Distance',group:'Activity',color:'#3679cc',unit:'km'}
}
const name=(key:string)=>meta[key]?.label??key.replaceAll('_',' ')
const unit=(m:Metric)=>m.unit??meta[m.metric_key]?.unit??''
const sourceName=(source:string)=>source.replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase())
const firstNameFrom=(user:{email?:string|null;user_metadata?:Record<string,unknown>})=>{
 const candidate=[user.user_metadata?.given_name,user.user_metadata?.name,user.user_metadata?.full_name,user.email?.split('@')[0]].find(value=>typeof value==='string'&&value.trim()) as string|undefined
 return (candidate??'Your').trim().split(/[\s._-]+/)[0].replace(/^./,letter=>letter.toUpperCase())
}
const number=(v:number,u?:string|null)=>`${Number(v.toFixed(Math.abs(v)>=100?0:1)).toLocaleString('en-GB')}${u?` ${u}`:''}`
const date=(d:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:TZ,day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${d}T12:00:00Z`))
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())

export function App(){
 const [metrics,setMetrics]=useState<Metric[]>([]),[notes,setNotes]=useState<Note[]>([]),[email,setEmail]=useState<string|null>(null),[firstName,setFirstName]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[view,setView]=useState<View>('dashboard'),[theme,setTheme]=useState<Theme>('light'),[selected,setSelected]=useState(['weight','waist']),[range,setRange]=useState(90),[rolling,setRolling]=useState(true),[columns,setColumns]=useState(['weight','waist','body_fat','muscle','steps','heart_rate']),[add,setAdd]=useState(false)
 const load=async()=>{if(!supabase){setError('This deployment still needs its Supabase public configuration.');setLoading(false);return};const {data:{session}}=await supabase.auth.getSession();if(!session){setLoading(false);return};setEmail(session.user.email??null);setFirstName(firstNameFrom(session.user));const [m,n,p]=await Promise.all([supabase.from('dashboard_metrics').select('*').order('source_timestamp',{ascending:false}).limit(5000),supabase.from('health_notes').select('*').order('local_date',{ascending:false}).limit(500),supabase.from('health_preferences').select('theme').eq('owner_id',session.user.id).maybeSingle()]);if(m.error)setError(m.error.message);else setMetrics(m.data as Metric[]);if(n.error)setError(n.error.message);else setNotes((n.data??[])as Note[]);if(p.data?.theme)setTheme(p.data.theme as Theme);setLoading(false)}
 useEffect(()=>{void load()},[])
 const available=useMemo(()=>[...new Set(metrics.map(m=>m.metric_key))].sort((a,b)=>name(a).localeCompare(name(b))),[metrics]);const ordered=useMemo(()=>[...metrics].sort((a,b)=>b.source_timestamp.localeCompare(a.source_timestamp)),[metrics]);const latest=useMemo(()=>Object.values(ordered.reduce<Record<string,Metric>>((a,m)=>{if(!a[m.metric_key])a[m.metric_key]=m;return a},{})),[ordered]);const dates=useMemo(()=>[...new Set([...metrics.map(m=>m.local_date),...notes.map(n=>n.local_date)])].sort().reverse(),[metrics,notes])
 const signIn=()=>supabase?.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}})
 const saveMetric=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget),d=String(f.get('date')),k=String(f.get('metric')),v=Number(f.get('value')),{data:{user}}=await supabase.auth.getUser();if(!user||!Number.isFinite(v))return;const r=await supabase.from('health_manual_metrics').insert({owner_id:user.id,local_date:d,source_timestamp:`${d}T12:00:00.000Z`,metric_key:k,value_numeric:v,unit:meta[k]?.unit??null,note:String(f.get('note')||'')||null});if(r.error)setError(r.error.message);else{setAdd(false);await load()}}
 const saveNote=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget),note=String(f.get('note')||'').trim(),d=String(f.get('date')),{data:{user}}=await supabase.auth.getUser();if(!user||!note)return;const r=await supabase.from('health_notes').insert({owner_id:user.id,local_date:d,note});if(r.error)setError(r.error.message);else{e.currentTarget.reset();await load()}}
 if(loading)return <main className="shell"><p>Loading your health data…</p></main>
 if(!email)return <main className="shell hero"><p className="eyebrow">BIOGRAPH</p><h1>Your health data, in one place.</h1><p>Sign in with the approved Google account to continue.</p><button onClick={signIn}>Continue with Google</button>{error&&<p className="error">{error}</p>}</main>
 const chooseTheme=async(next:Theme)=>{setTheme(next);const {data:{user}}=await supabase!.auth.getUser();if(user){const r=await supabase!.from('health_preferences').upsert({owner_id:user.id,theme:next,updated_at:new Date().toISOString()});if(r.error)setError(r.error.message)}}
 return <main className={`app theme-${theme}`}><header className="topbar"><div className="brand"><span className="brand-mark" style={{backgroundImage:`url(${biographLogoSheet})`}} aria-label="Biograph logo"/> Biograph</div><div className="top-actions"><label className="theme-picker">Appearance<select value={theme} onChange={e=>void chooseTheme(e.target.value as Theme)}><option value="light">Light</option><option value="dark">Dark</option><option value="permit">Cobalt</option><option value="aurora">Aurora</option></select></label><button onClick={()=>setAdd(true)}>+ Add entry</button><button className="quiet" onClick={()=>supabase?.auth.signOut().then(()=>location.reload())}>Sign out</button></div></header><div className="content"><section className="heading"><div><p className="eyebrow">{firstName}'s health journal</p><h1>{view==='dashboard'?'Health at a glance':view==='trends'?'Explore your trends':view==='daily'?'Every metric, by date':view==='records'?'Every measurement':'Sources & coverage'}</h1><p>Measurements, patterns, and the context behind them.</p></div><p className="stamp">Snapshot through {ordered[0]?date(ordered[0].local_date):'today'}<br/>{TZ}</p></section><p className="notice">Your data remains private. Source records and manual additions remain visible.</p><nav>{(['dashboard','trends','daily','records','sources']as View[]).map(v=><button key={v} className={view===v?'active':'quiet'} onClick={()=>setView(v)}>{v==='daily'?'Daily table':v[0].toUpperCase()+v.slice(1)}</button>)}</nav>{error&&<p className="error">{error}</p>}
 {view==='dashboard'&&<Dashboard metrics={metrics} cards={['weight','waist','body_fat','muscle','steps','heart_rate'].map(k=>latest.find(m=>m.metric_key===k)).filter(Boolean)as Metric[]} open={(keys)=>{setSelected(keys);setView('trends')}}/>}
 {view==='trends'&&<Trends metrics={metrics} available={available} selected={selected} setSelected={setSelected} range={range} setRange={setRange} rolling={rolling} setRolling={setRolling}/>} {view==='daily'&&<Daily metrics={metrics} notes={notes} dates={dates} available={available} columns={columns} setColumns={setColumns} saveNote={saveNote}/>} {view==='records'&&<Records metrics={ordered}/>} {view==='sources'&&<Sources metrics={metrics}/>}</div>{add&&<Modal available={available} close={()=>setAdd(false)} save={saveMetric}/>}</main>
}
function Dashboard({metrics,cards,open}:{metrics:Metric[];cards:Metric[];open:(k:string[])=>void}){return <><section className="cards">{cards.map(m=>{const s=metrics.filter(x=>x.metric_key===m.metric_key).slice(0,12).reverse(),first=s[0]?.value_numeric,change=first===undefined?null:m.value_numeric-first;return <button className="card" style={{'--metric':meta[m.metric_key]?.color}as React.CSSProperties} key={m.metric_key} onClick={()=>open([m.metric_key])}><span className="category">{meta[m.metric_key]?.group??'Metric'}</span><strong>{number(m.value_numeric,unit(m))}</strong><span>{name(m.metric_key)}</span><Spark data={s} color={meta[m.metric_key]?.color??'#6659d8'}/><small className="delta">{change===null?'First reading':`${change>=0?'+':''}${number(change,unit(m))} in displayed history`}</small></button>})}</section><section className="grid2"><article className="panel"><Title eyebrow="BODY" title="Weight & abdominal perimeter" action={()=>open(['weight','waist'])}/><Chart metrics={metrics} keys={['weight','waist']} days={365} relative/><p className="caption">Relative change makes different units comparable.</p></article><article className="panel"><Title eyebrow="COMPOSITION" title="Fat & muscle" action={()=>open(['body_fat','muscle'])}/><Chart metrics={metrics} keys={['body_fat','muscle']} days={365}/><p className="caption">Measurements retain their original source and provenance.</p></article></section><article className="panel callout"><div><strong>Keep the context with the numbers.</strong><p>Add a dated note or one-off measurement for a device, training or health change.</p></div><p>{metrics.length.toLocaleString('en-GB')} normalized readings</p></article></>}
function Trends({metrics,available,selected,setSelected,range,setRange,rolling,setRolling}:{metrics:Metric[];available:string[];selected:string[];setSelected:(x:string[])=>void;range:number;setRange:(x:number)=>void;rolling:boolean;setRolling:(x:boolean)=>void}){const toggle=(k:string)=>setSelected(selected.includes(k)?selected.length>1?selected.filter(x=>x!==k):selected:selected.length<6?[...selected,k]:selected);return <><section className="panel controls"><div><label>Range <select value={range} onChange={e=>setRange(+e.target.value)}><option value="30">30 days</option><option value="90">90 days</option><option value="365">Year</option><option value="5000">All time</option></select></label><label className="check"><input type="checkbox" checked={rolling} onChange={e=>setRolling(e.target.checked)}/> 7-day rolling mean</label></div><details><summary>Choose metrics · up to 6</summary><div className="picker">{available.map(k=><label key={k}><input type="checkbox" checked={selected.includes(k)} onChange={()=>toggle(k)}/>{name(k)}</label>)}</div></details></section><section className="panel"><Title eyebrow="COMPARISON" title={selected.map(name).join(' · ')}/><Chart metrics={metrics} keys={selected} days={range} rolling={rolling} tall/><div className="statgrid">{selected.map(k=>{const s=metrics.filter(m=>m.metric_key===k).sort((a,b)=>a.source_timestamp.localeCompare(b.source_timestamp)),last=s.at(-1),first=s[0],mean=s.slice(-7).reduce((a,m)=>a+m.value_numeric,0)/(Math.min(7,s.length)||1);return <div key={k}><span>{name(k)}</span><strong>{last?number(last.value_numeric,unit(last)):'—'}</strong><small>{last&&first?`${last.value_numeric-first.value_numeric>=0?'+':''}${number(last.value_numeric-first.value_numeric,unit(last))} period · 7D ${number(mean,unit(last))}`:'—'}</small></div>})}</div></section></>}
function Daily({metrics,notes,dates,available,columns,setColumns,saveNote}:{metrics:Metric[];notes:Note[];dates:string[];available:string[];columns:string[];setColumns:(x:string[])=>void;saveNote:(e:FormEvent<HTMLFormElement>)=>void}){const move=(k:string,d:number)=>{const i=columns.indexOf(k),n=i+d;if(n<0||n>=columns.length)return;const c=[...columns];[c[i],c[n]]=[c[n],c[i]];setColumns(c)};return <><section className="panel"><Title eyebrow="CUSTOMISE" title="Columns"/><div className="picker compact">{available.map(k=><label key={k}><input type="checkbox" checked={columns.includes(k)} onChange={()=>setColumns(columns.includes(k)?columns.filter(x=>x!==k):[...columns,k])}/>{name(k)}</label>)}</div></section><section className="panel table-panel"><p className="caption">{dates.length} dates · {columns.length} selected columns · scroll horizontally on small screens.</p><div className="tablewrap"><table><thead><tr><th>Date</th>{columns.map((k,i)=><th key={k}><span>{name(k)}</span><div><button disabled={!i} onClick={()=>move(k,-1)}>←</button><button disabled={i===columns.length-1} onClick={()=>move(k,1)}>→</button><button onClick={()=>setColumns(columns.filter(x=>x!==k))}>×</button></div></th>)}<th>Notes</th></tr></thead><tbody>{dates.map(d=><tr key={d}><th>{date(d)}</th>{columns.map(k=><td key={k}>{metrics.filter(m=>m.local_date===d&&m.metric_key===k).slice(0,4).map((m,i)=><div className="reading" key={i}><strong>{number(m.value_numeric,unit(m))}</strong><small>{sourceName(m.source)}</small></div>)||'—'}</td>)}<td>{notes.filter(n=>n.local_date===d).map(n=><p className="note" key={n.id}>{n.note}</p>)}</td></tr>)}</tbody></table></div></section><section className="panel"><h2>Add a note</h2><form className="noteform" onSubmit={saveNote}><input type="date" name="date" defaultValue={today()} required/><input name="note" placeholder="What matters about this date?" required/><button>Save note</button></form></section></>}
function Records({metrics}:{metrics:Metric[]}){const [filter,setFilter]=useState('all'),rows=filter==='all'?metrics:metrics.filter(m=>m.metric_key===filter);return <section className="panel table-panel"><div className="panel-title"><div><p className="eyebrow">RAW NORMALIZED RECORDS</p><h2>Every measurement</h2></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All metrics</option>{[...new Set(metrics.map(m=>m.metric_key))].sort().map(k=><option key={k}>{k}</option>)}</select></div><div className="tablewrap"><table><thead><tr><th>Date & time</th><th>Metric</th><th>Value</th><th>Source</th><th>Kind</th></tr></thead><tbody>{rows.map((m,i)=><tr key={i}><td>{new Date(m.source_timestamp).toLocaleString('en-GB',{timeZone:TZ})}</td><td>{name(m.metric_key)}</td><td><strong>{number(m.value_numeric,unit(m))}</strong></td><td>{sourceName(m.source)}</td><td>{m.is_derived?'Derived':'Recorded'}</td></tr>)}</tbody></table></div></section>}
function Sources({metrics}:{metrics:Metric[]}){return <section className="sourcegrid">{[...new Set(metrics.map(m=>m.source))].map(s=>{const rows=metrics.filter(m=>m.source===s);return <article className="panel" key={s}><p className="eyebrow">DATA SOURCE</p><h2>{sourceName(s)}</h2><p>{rows.length.toLocaleString('en-GB')} normalized values · latest {rows[0]?date(rows[0].local_date):'—'}</p><p className="caption">Source provenance stays retained for audit and reprocessing.</p></article>})}<article className="panel"><p className="eyebrow">INGESTION POLICY</p><h2>Sources remain connected</h2><p>Original records stay available alongside normalized measurements.</p></article></section>}
function Modal({available,close,save}:{available:string[];close:()=>void;save:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="modalback"><section className="modal"><div className="panel-title"><h2>Add a measurement</h2><button className="quiet" onClick={close}>×</button></div><form className="entryform" onSubmit={save}><label>Date<input type="date" name="date" defaultValue={today()} required/></label><label>Metric<select name="metric">{available.map(k=><option key={k} value={k}>{name(k)}{meta[k]?.unit?` (${meta[k].unit})`:''}</option>)}</select></label><label>Value<input type="number" name="value" step="any" required/></label><label>Context<input name="note" placeholder="Optional note"/></label><button>Save measurement</button></form></section></div>}
function Title({eyebrow,title,action}:{eyebrow:string;title:string;action?:()=>void}){return <div className="panel-title"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{action&&<button className="quiet" onClick={action}>Compare</button>}</div>}
function Spark({data,color}:{data:Metric[];color:string}){if(!data.length)return null;const v=data.map(x=>x.value_numeric),lo=Math.min(...v),span=Math.max(Math.max(...v)-lo,.001),points=data.map((m,i)=>`${data.length===1?50:i/(data.length-1)*100},${92-(m.value_numeric-lo)/span*75}`).join(' ');return <svg className="spark" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={points} style={{stroke:color}}/></svg>}
function Chart({metrics,keys,days,relative=false,rolling=false,tall=false}:{metrics:Metric[];keys:string[];days:number;relative?:boolean;rolling?:boolean;tall?:boolean}){const series=keys.map(k=>metrics.filter(m=>m.metric_key===k).slice(0,days>=5000?5000:Math.max(days,30)).reverse()).filter(x=>x.length);if(!series.length)return <p className="empty">No comparable measurements yet.</p>;const lanes=relative||new Set(series.map(x=>unit(x[0]))).size===1?[series]:series.map(x=>[x]);return <div className={tall?'charts tall':'charts'}>{lanes.map((lane,i)=><Lane lane={lane} relative={relative} rolling={rolling} key={i}/>)}</div>}
function Lane({lane,relative,rolling}:{lane:Metric[][];relative:boolean;rolling:boolean}){const vals=lane.flatMap(s=>s.map(m=>relative?(m.value_numeric/s[0].value_numeric-1)*100:m.value_numeric)),lo=Math.min(...vals),span=Math.max(Math.max(...vals)-lo,.01),line=(s:Metric[])=>s.map((m,i)=>{const v=relative?(m.value_numeric/s[0].value_numeric-1)*100:m.value_numeric;return `${s.length===1?30:30+i/(s.length-1)*670},${210-(v-lo)/span*170}`}).join(' ');return <svg className="chart" viewBox="0 0 720 250"><line x1="30" x2="700" y1="210" y2="210"/><line x1="30" x2="700" y1="125" y2="125"/><line x1="30" x2="700" y1="40" y2="40"/>{lane.map(s=><g key={s[0].metric_key}><polyline points={line(s)} style={{stroke:meta[s[0].metric_key]?.color??'#6659d8'}}/>{rolling&&s.length>6&&<polyline className="roll" points={line(s.slice(6))} style={{stroke:meta[s[0].metric_key]?.color??'#6659d8'}}/>}<text x="32" y="24">{name(s[0].metric_key)}{relative?' · % change':` · ${unit(s[0])}`}</text></g>)}</svg>}
